load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "friction_coefficient",
    srcs = ["friction_coefficient.py"],
    visibility = ["//ccpd:__subpackages__"],
    deps = [
        "@python_deps_colorama//:pkg",
        "@python_deps_numpy//:pkg",
    ],
)
