py_library(
    name = "centrifugal_calcs",
    srcs = ["centrifugal_calcs.py"],
    data = ["//ccpd/fluids:fluids.json"],
    visibility = ["//ccpd:__subpackages__"],
    deps = [
        "//ccpd/data_types:centrifugal_compressor",
        "//ccpd/data_types:inputs",
        "//ccpd/data_types:working_fluid",
    ],
)
