load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "tip_diameter_tests",
    srcs = ["tip_diameter_tests.py"],
    deps = [
        "//ccpd/utilities:tip_diameter",
    ],
)

py_test(
    name = "inlet_loop_calcs_tests",
    srcs = ["inlet_loop_calcs_tests.py"],
    deps = [
        "//ccpd/utilities:inlet_loop_calcs",
    ],
)
