py_library(
    name = "thermo_point",
    srcs = ["thermo_point.py"],
    visibility = ["//ccpd:__subpackages__"],
)

py_library(
    name = "inputs",
    srcs = ["inputs.py"],
    visibility = ["//ccpd:__subpackages__"],
)
