# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    types: [opened, labeled, synchronize, edited]
  issue_comment:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a multiple jobs
  bazel-build-ccpd:
    if: contains(github.event.pull_request.labels.*.name, 'check')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: aevalenc/Centrifugal-Compressor-Preliminary-Design
          submodules: true
      - uses: actions/checkout@v3
        with:
          path: ccpd
          ref: ${{github.event.pull_request.head.ref}}
      - uses: bazelbuild/setup-bazelisk@v1
      - run: |
          bazel build //ccpd/...

  bazel-build-ccpd-with_comment:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/recheck') # check the comment if it contains the keywords
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: aevalenc/Centrifugal-Compressor-Preliminary-Design
          submodules: true
      - uses: actions/checkout@v3
        with:
          path: ccpd
          ref: ${{github.event.pull_request.head.ref}}
      - uses: bazelbuild/setup-bazelisk@v1
      - run: |
          bazel build //ccpd/...

  bazel-test-ccpd:
    if: contains(github.event.pull_request.labels.*.name, 'check')
    needs: bazel-build-ccpd

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: aevalenc/Centrifugal-Compressor-Preliminary-Design
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          path: ccpd
          ref: ${{github.event.pull_request.head.ref}}
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel test --cache_test_results=no --test_output=all //ccpd/...

  bazel-run-ccpd-main:
    if: contains(github.event.pull_request.labels.*.name, 'check')
    needs: bazel-build-ccpd

    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: aevalenc/Centrifugal-Compressor-Preliminary-Design
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          path: ccpd
          ref: ${{github.event.pull_request.head.ref}}
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel run //ccpd:main

  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
